URL_REQUIRED_ERROR = "URL обязателен"
URL_TOO_LONG_ERROR = "URL превышает 255 символов"
INCORRECT_URL_ERROR = "Некорректный URL"
URL_ADDED_SUCCESS = "Страница успешно добавлена"
URL_ALREADY_EXISTS = "Страница уже существует"
URL_CHECK_SUCCESS = "Страница успешно проверена"
